services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./docker-config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
